# Generated by Django 4.2.30 on 2026-05-05 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("report", "Report"),
                            ("observation", "Observation"),
                            ("note", "Clinical Note"),
                            ("treatment", "Treatment"),
                            ("timeline", "Timeline Event"),
                        ],
                        max_length=50,
                    ),
                ),
                ("source_id", models.PositiveIntegerField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("snippet", models.TextField()),
                ("evidence_date", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("confidence", models.FloatField(default=1.0)),
                ("reviewed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_items",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-evidence_date", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="SourceBackedObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("explanation", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("watch", "Watch"),
                            ("needs_review", "Needs Review"),
                        ],
                        default="info",
                        max_length=30,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("evidence_json", models.JSONField(blank=True, default=dict)),
                ("reviewed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evidence_items",
                    models.ManyToManyField(
                        blank=True,
                        related_name="source_observations",
                        to="evidence.evidenceitem",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_observations",
                        to="patients.patient",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchIndexEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_type", models.CharField(max_length=50)),
                ("source_id", models.PositiveIntegerField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("search_text", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_entries",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observation_type",
                    models.CharField(
                        choices=[
                            ("tumor_marker", "Tumor Marker"),
                            ("lab", "Lab"),
                            ("vital", "Vital"),
                            ("biomarker", "Biomarker"),
                            ("symptom", "Symptom"),
                            ("imaging_language", "Imaging Language"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("value_text", models.CharField(blank=True, max_length=255)),
                ("value_number", models.FloatField(blank=True, null=True)),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("observed_at", models.DateField(blank=True, null=True)),
                ("source_snippet", models.TextField(blank=True)),
                ("confidence", models.FloatField(default=1.0)),
                (
                    "confirmation_status",
                    models.CharField(
                        choices=[
                            ("unconfirmed", "Unconfirmed"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                        ],
                        default="unconfirmed",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="observations",
                        to="patients.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="patients.patient",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="observations",
                        to="reports.diagnosticreport",
                    ),
                ),
            ],
            options={
                "ordering": ["-observed_at", "-pk"],
            },
        ),
    ]
