# Generated by Django 4.2.30 on 2026-05-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchindexentry",
            name="embedding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
